# syntax=docker/dockerfile:1

FROM python:3.12-slim

WORKDIR /locust

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install locust

COPY . .

EXPOSE 8089

CMD ["locust", "-f", "locust.py", "--host=http://fastapi:8000"]
